// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum CreateRoomError : ushort
{
  SUCCESS = 0,
  OVERLAPPED = 1,
  INVALID_ID = 2,
  UNKNOWN = 3,
};

