// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RoomInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static RoomInfo GetRootAsRoomInfo(ByteBuffer _bb) { return GetRootAsRoomInfo(_bb, new RoomInfo()); }
  public static RoomInfo GetRootAsRoomInfo(ByteBuffer _bb, RoomInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoomInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int RoomId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Level { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Password { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPasswordBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPasswordArray() { return __p.__vector_as_array<byte>(8); }
  public int MemberCount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<RoomInfo> CreateRoomInfo(FlatBufferBuilder builder,
      int roomId = 0,
      int level = 0,
      StringOffset passwordOffset = default(StringOffset),
      int memberCount = 0) {
    builder.StartTable(4);
    RoomInfo.AddMemberCount(builder, memberCount);
    RoomInfo.AddPassword(builder, passwordOffset);
    RoomInfo.AddLevel(builder, level);
    RoomInfo.AddRoomId(builder, roomId);
    return RoomInfo.EndRoomInfo(builder);
  }

  public static void StartRoomInfo(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddRoomId(FlatBufferBuilder builder, int roomId) { builder.AddInt(0, roomId, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(1, level, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(2, passwordOffset.Value, 0); }
  public static void AddMemberCount(FlatBufferBuilder builder, int memberCount) { builder.AddInt(3, memberCount, 0); }
  public static Offset<RoomInfo> EndRoomInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<RoomInfo>(o);
  }
}


static public class RoomInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*RoomId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Level*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*Password*/, false)
      && verifier.VerifyField(tablePos, 10 /*MemberCount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
