// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum EnterRoomError : ushort
{
  SUCCESS = 0,
  FULL = 1,
  NOT_FOUND = 2,
  UNKNOWN = 3,
};

