// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S_LeaveRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static S_LeaveRoom GetRootAsS_LeaveRoom(ByteBuffer _bb) { return GetRootAsS_LeaveRoom(_bb, new S_LeaveRoom()); }
  public static S_LeaveRoom GetRootAsS_LeaveRoom(ByteBuffer _bb, S_LeaveRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S_LeaveRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<S_LeaveRoom> CreateS_LeaveRoom(FlatBufferBuilder builder,
      int id = 0) {
    builder.StartTable(1);
    S_LeaveRoom.AddId(builder, id);
    return S_LeaveRoom.EndS_LeaveRoom(builder);
  }

  public static void StartS_LeaveRoom(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static Offset<S_LeaveRoom> EndS_LeaveRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<S_LeaveRoom>(o);
  }
}


static public class S_LeaveRoomVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
