// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S_CreateRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static S_CreateRoom GetRootAsS_CreateRoom(ByteBuffer _bb) { return GetRootAsS_CreateRoom(_bb, new S_CreateRoom()); }
  public static S_CreateRoom GetRootAsS_CreateRoom(ByteBuffer _bb, S_CreateRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S_CreateRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CreateRoomError Ok { get { int o = __p.__offset(4); return o != 0 ? (CreateRoomError)__p.bb.Get(o + __p.bb_pos) : CreateRoomError.SUCCESS; } }

  public static Offset<S_CreateRoom> CreateS_CreateRoom(FlatBufferBuilder builder,
      CreateRoomError ok = CreateRoomError.SUCCESS) {
    builder.StartTable(1);
    S_CreateRoom.AddOk(builder, ok);
    return S_CreateRoom.EndS_CreateRoom(builder);
  }

  public static void StartS_CreateRoom(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOk(FlatBufferBuilder builder, CreateRoomError ok) { builder.AddByte(0, (byte)ok, 0); }
  public static Offset<S_CreateRoom> EndS_CreateRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<S_CreateRoom>(o);
  }
}


static public class S_CreateRoomVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ok*/, 1 /*CreateRoomError*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
