// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_EnterRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static C_EnterRoom GetRootAsC_EnterRoom(ByteBuffer _bb) { return GetRootAsC_EnterRoom(_bb, new C_EnterRoom()); }
  public static C_EnterRoom GetRootAsC_EnterRoom(ByteBuffer _bb, C_EnterRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_EnterRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int RoomId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<C_EnterRoom> CreateC_EnterRoom(FlatBufferBuilder builder,
      int room_Id = 0) {
    builder.StartTable(1);
    C_EnterRoom.AddRoomId(builder, room_Id);
    return C_EnterRoom.EndC_EnterRoom(builder);
  }

  public static void StartC_EnterRoom(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRoomId(FlatBufferBuilder builder, int roomId) { builder.AddInt(0, roomId, 0); }
  public static Offset<C_EnterRoom> EndC_EnterRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_EnterRoom>(o);
  }
}


static public class C_EnterRoomVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*RoomId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
