// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S_Spawn : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static S_Spawn GetRootAsS_Spawn(ByteBuffer _bb) { return GetRootAsS_Spawn(_bb, new S_Spawn()); }
  public static S_Spawn GetRootAsS_Spawn(ByteBuffer _bb, S_Spawn obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S_Spawn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public pos_info? Pos { get { int o = __p.__offset(6); return o != 0 ? (pos_info?)(new pos_info()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<S_Spawn> CreateS_Spawn(FlatBufferBuilder builder,
      int id = 0,
      Offset<pos_info> posOffset = default(Offset<pos_info>)) {
    builder.StartTable(2);
    S_Spawn.AddPos(builder, posOffset);
    S_Spawn.AddId(builder, id);
    return S_Spawn.EndS_Spawn(builder);
  }

  public static void StartS_Spawn(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<pos_info> posOffset) { builder.AddOffset(1, posOffset.Value, 0); }
  public static Offset<S_Spawn> EndS_Spawn(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<S_Spawn>(o);
  }
}


static public class S_SpawnVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*Pos*/, pos_infoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
