// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum CreateRoomError : byte
{
  SUCCESS = 0,
  INVALID_PW = 1,
  INVALID_TITLE = 2,
  UNKNOWN = 3,
};

